@url = http://localhost:8080


// perfil = 1 => Administrador, perfil = 2 => usuarios
@perfil = 1

GET {{url}}/productos HTTP/1.1
perfil: {{perfil}}

GET {{url}}/productos/1 HTTP/1.1
perfil: {{perfil}}

POST {{url}}/productos HTTP/1.1
Content-Type: application/json
perfil: {{perfil}}

{
  "nombre": "Mayonesa Hellmans",
  "descripcion": "Mayonesa Hellmans Premium 2.75kg",
  "codigo": "mayo1",
  "foto": "https://http2.mlstatic.com/D_NQ_NP_2X_706878-MLA45106019219_032021-F.webp",
  "precio": 25.8,
  "stock": 250
}

PUT {{url}}/productos/1 HTTP/1.1
Content-Type: application/json
perfil: {{perfil}}

{
  "nombre": "Mayonesa Hellmans 2",
  "descripcion": "Mayonesa Hellmans Premium 2.75kg",
  "codigo": "mayo1",
  "foto": "https://http2.mlstatic.com/D_NQ_NP_2X_706878-MLA45106019219_032021-F.webp",
  "precio": 25.8,
  "stock": 250
}

DELETE  {{url}}/productos/1 HTTP/1.1
perfil: {{perfil}}


// carritos

GET {{url}}/carritos HTTP/1.1
perfil: {{perfil}}

GET {{url}}/carritos/1 HTTP/1.1
perfil: {{perfil}}

PUT {{url}}/carritos/1/2 HTTP/1.1
Content-Type: application/json
perfil: {{perfil}}

DELETE {{url}}/carritos/1/2 HTTP/1.1
Content-Type: application/json
perfil: {{perfil}}